[package]
name = "celari_passkey_account"
type = "contract"
authors = ["Celari Team"]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v3.0.3", directory = "noir-projects/aztec-nr/aztec" }
sha256 = { tag = "v0.3.0", git = "https://github.com/noir-lang/sha256" }
